packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - style-dictionary
  - unrs-resolver

overrides:
  use-tiptap: link:../../../../../Library/pnpm/global/5/node_modules/use-tiptap
  list: link:../../../../../Library/pnpm/global/5/node_modules/list
