
/* ------------------------------------------------------------ */
/*                        Icon Registry                        */
/* ------------------------------------------------------------ */
/* 
 * Auto-generated by nuxt-compose-icons.
 * Feel free to version this file, but do not edit directly as it will be overwritten at build time. 
 */

import type { Component } from 'vue';
import AjouterIcon from './AjouterIcon';
import ArticleIcon from './ArticleIcon';
import BoiteAQuestion2Icon from './BoiteAQuestion2Icon';
import BoiteAQuestionIcon from './BoiteAQuestionIcon';
import BookmarkIcon from './BookmarkIcon';
import BoutonFBIcon from './BoutonFBIcon';
import BoutonInstaIcon from './BoutonInstaIcon';
import BoutonTwitterIcon from './BoutonTwitterIcon';
import BrouillonIcon from './BrouillonIcon';
import ClocheIcon from './ClocheIcon';
import CroixFermerIcon from './CroixFermerIcon';
import CuicuiIcon from './CuicuiIcon';
import DevelopperIcon from './DevelopperIcon';
import EditIcon from './EditIcon';
import EnveloppeIcon from './EnveloppeIcon';
import FacebookIcon from './FacebookIcon';
import FIcon from './FIcon';
import FlecheIcon from './FlecheIcon';
import FlecheRetourIcon from './FlecheRetourIcon';
import Group37Icon from './Group37Icon';
import Group38Icon from './Group38Icon';
import GroupeIcon from './GroupeIcon';
import ImportIcon from './ImportIcon';
import InstagramIcon from './InstagramIcon';
import InstaIcon from './InstaIcon';
import LexiqueIcon from './LexiqueIcon';
import LinkIcon from './LinkIcon';
import LogoIcon from './LogoIcon';
import LoupeIcon from './LoupeIcon';
import MegaphoneIcon from './MegaphoneIcon';
import MessageIcon from './MessageIcon';
import PersonnagesClesIcon from './PersonnagesClesIcon';
import PictosCartes01Icon from './PictosCartes01Icon';
import PictosCartes02Icon from './PictosCartes02Icon';
import PictosCartes03Icon from './PictosCartes03Icon';
import PictosCartes04Icon from './PictosCartes04Icon';
import PictosCartes05Icon from './PictosCartes05Icon';
import PictosCartes06Icon from './PictosCartes06Icon';
import PictosEditeurAjouterImageIcon from './PictosEditeurAjouterImageIcon';
import PictosEditeurAjouterLienIcon from './PictosEditeurAjouterLienIcon';
import PictosEditeurAlignerDroiteIcon from './PictosEditeurAlignerDroiteIcon';
import PictosEditeurAlignerGaucheIcon from './PictosEditeurAlignerGaucheIcon';
import PictosEditeurAlignerMilieuIcon from './PictosEditeurAlignerMilieuIcon';
import PictosEditeurCitationIcon from './PictosEditeurCitationIcon';
import PictosEditeurCommentaireIcon from './PictosEditeurCommentaireIcon';
import PictosEditeurCouleurBlancIcon from './PictosEditeurCouleurBlancIcon';
import PictosEditeurCouleurNoirIcon from './PictosEditeurCouleurNoirIcon';
import PictosEditeurCouleurRougeIcon from './PictosEditeurCouleurRougeIcon';
import PictosEditeurDeroulerIcon from './PictosEditeurDeroulerIcon';
import PictosEditeurEncartIcon from './PictosEditeurEncartIcon';
import PictosEditeurGrasIcon from './PictosEditeurGrasIcon';
import PictosEditeurItaliqueIcon from './PictosEditeurItaliqueIcon';
import PictosEditeurParagrapheIcon from './PictosEditeurParagrapheIcon';
import PictosEditeurPucesIcon from './PictosEditeurPucesIcon';
import PictosEditeurSouligneIcon from './PictosEditeurSouligneIcon';
import PictosEditeurSurlignageBlancIcon from './PictosEditeurSurlignageBlancIcon';
import PictosEditeurSurlignageNoirIcon from './PictosEditeurSurlignageNoirIcon';
import PictosEditeurSurlignageRougeIcon from './PictosEditeurSurlignageRougeIcon';
import PictosEditeurTitre1Icon from './PictosEditeurTitre1Icon';
import PictosEditeurTitre2Icon from './PictosEditeurTitre2Icon';
import PictosEditeurTraitIcon from './PictosEditeurTraitIcon';
import PictosModulesAnonymeIcon from './PictosModulesAnonymeIcon';
import PictosModulesChronologieIcon from './PictosModulesChronologieIcon';
import PictosModulesMettreEnAvantIcon from './PictosModulesMettreEnAvantIcon';
import PictosModulesValiderIcon from './PictosModulesValiderIcon';
import Placeholder01Icon from './Placeholder01Icon';
import PoingIcon from './PoingIcon';
import ProfilIcon from './ProfilIcon';
import ReduireIcon from './ReduireIcon';
import RevueDePresseIcon from './RevueDePresseIcon';
import SaveIcon from './SaveIcon';
import TexteIcon from './TexteIcon';
import TrashIcon from './TrashIcon';
import TwitterIcon from './TwitterIcon';

export interface IconRegistryEntry {
  name: string;
  pascalName: string;
  kebabName: string;
  importPath: string;
  component: Component;
}

export const iconRegistry: IconRegistryEntry[] = [
  { name: 'AjouterIcon', pascalName: 'AjouterIcon', kebabName: 'ajouter-icon', importPath: './AjouterIcon', component: AjouterIcon },
  { name: 'ArticleIcon', pascalName: 'ArticleIcon', kebabName: 'article-icon', importPath: './ArticleIcon', component: ArticleIcon },
  { name: 'BoiteAQuestion2Icon', pascalName: 'BoiteAQuestion2Icon', kebabName: 'boite-aquestion2icon', importPath: './BoiteAQuestion2Icon', component: BoiteAQuestion2Icon },
  { name: 'BoiteAQuestionIcon', pascalName: 'BoiteAQuestionIcon', kebabName: 'boite-aquestion-icon', importPath: './BoiteAQuestionIcon', component: BoiteAQuestionIcon },
  { name: 'BookmarkIcon', pascalName: 'BookmarkIcon', kebabName: 'bookmark-icon', importPath: './BookmarkIcon', component: BookmarkIcon },
  { name: 'BoutonFBIcon', pascalName: 'BoutonFBIcon', kebabName: 'bouton-fbicon', importPath: './BoutonFBIcon', component: BoutonFBIcon },
  { name: 'BoutonInstaIcon', pascalName: 'BoutonInstaIcon', kebabName: 'bouton-insta-icon', importPath: './BoutonInstaIcon', component: BoutonInstaIcon },
  { name: 'BoutonTwitterIcon', pascalName: 'BoutonTwitterIcon', kebabName: 'bouton-twitter-icon', importPath: './BoutonTwitterIcon', component: BoutonTwitterIcon },
  { name: 'BrouillonIcon', pascalName: 'BrouillonIcon', kebabName: 'brouillon-icon', importPath: './BrouillonIcon', component: BrouillonIcon },
  { name: 'ClocheIcon', pascalName: 'ClocheIcon', kebabName: 'cloche-icon', importPath: './ClocheIcon', component: ClocheIcon },
  { name: 'CroixFermerIcon', pascalName: 'CroixFermerIcon', kebabName: 'croix-fermer-icon', importPath: './CroixFermerIcon', component: CroixFermerIcon },
  { name: 'CuicuiIcon', pascalName: 'CuicuiIcon', kebabName: 'cuicui-icon', importPath: './CuicuiIcon', component: CuicuiIcon },
  { name: 'DevelopperIcon', pascalName: 'DevelopperIcon', kebabName: 'developper-icon', importPath: './DevelopperIcon', component: DevelopperIcon },
  { name: 'EditIcon', pascalName: 'EditIcon', kebabName: 'edit-icon', importPath: './EditIcon', component: EditIcon },
  { name: 'EnveloppeIcon', pascalName: 'EnveloppeIcon', kebabName: 'enveloppe-icon', importPath: './EnveloppeIcon', component: EnveloppeIcon },
  { name: 'FacebookIcon', pascalName: 'FacebookIcon', kebabName: 'facebook-icon', importPath: './FacebookIcon', component: FacebookIcon },
  { name: 'FIcon', pascalName: 'FIcon', kebabName: 'ficon', importPath: './FIcon', component: FIcon },
  { name: 'FlecheIcon', pascalName: 'FlecheIcon', kebabName: 'fleche-icon', importPath: './FlecheIcon', component: FlecheIcon },
  { name: 'FlecheRetourIcon', pascalName: 'FlecheRetourIcon', kebabName: 'fleche-retour-icon', importPath: './FlecheRetourIcon', component: FlecheRetourIcon },
  { name: 'Group37Icon', pascalName: 'Group37Icon', kebabName: 'group37icon', importPath: './Group37Icon', component: Group37Icon },
  { name: 'Group38Icon', pascalName: 'Group38Icon', kebabName: 'group38icon', importPath: './Group38Icon', component: Group38Icon },
  { name: 'GroupeIcon', pascalName: 'GroupeIcon', kebabName: 'groupe-icon', importPath: './GroupeIcon', component: GroupeIcon },
  { name: 'ImportIcon', pascalName: 'ImportIcon', kebabName: 'import-icon', importPath: './ImportIcon', component: ImportIcon },
  { name: 'InstagramIcon', pascalName: 'InstagramIcon', kebabName: 'instagram-icon', importPath: './InstagramIcon', component: InstagramIcon },
  { name: 'InstaIcon', pascalName: 'InstaIcon', kebabName: 'insta-icon', importPath: './InstaIcon', component: InstaIcon },
  { name: 'LexiqueIcon', pascalName: 'LexiqueIcon', kebabName: 'lexique-icon', importPath: './LexiqueIcon', component: LexiqueIcon },
  { name: 'LinkIcon', pascalName: 'LinkIcon', kebabName: 'link-icon', importPath: './LinkIcon', component: LinkIcon },
  { name: 'LogoIcon', pascalName: 'LogoIcon', kebabName: 'logo-icon', importPath: './LogoIcon', component: LogoIcon },
  { name: 'LoupeIcon', pascalName: 'LoupeIcon', kebabName: 'loupe-icon', importPath: './LoupeIcon', component: LoupeIcon },
  { name: 'MegaphoneIcon', pascalName: 'MegaphoneIcon', kebabName: 'megaphone-icon', importPath: './MegaphoneIcon', component: MegaphoneIcon },
  { name: 'MessageIcon', pascalName: 'MessageIcon', kebabName: 'message-icon', importPath: './MessageIcon', component: MessageIcon },
  { name: 'PersonnagesClesIcon', pascalName: 'PersonnagesClesIcon', kebabName: 'personnages-cles-icon', importPath: './PersonnagesClesIcon', component: PersonnagesClesIcon },
  { name: 'PictosCartes01Icon', pascalName: 'PictosCartes01Icon', kebabName: 'pictos-cartes01icon', importPath: './PictosCartes01Icon', component: PictosCartes01Icon },
  { name: 'PictosCartes02Icon', pascalName: 'PictosCartes02Icon', kebabName: 'pictos-cartes02icon', importPath: './PictosCartes02Icon', component: PictosCartes02Icon },
  { name: 'PictosCartes03Icon', pascalName: 'PictosCartes03Icon', kebabName: 'pictos-cartes03icon', importPath: './PictosCartes03Icon', component: PictosCartes03Icon },
  { name: 'PictosCartes04Icon', pascalName: 'PictosCartes04Icon', kebabName: 'pictos-cartes04icon', importPath: './PictosCartes04Icon', component: PictosCartes04Icon },
  { name: 'PictosCartes05Icon', pascalName: 'PictosCartes05Icon', kebabName: 'pictos-cartes05icon', importPath: './PictosCartes05Icon', component: PictosCartes05Icon },
  { name: 'PictosCartes06Icon', pascalName: 'PictosCartes06Icon', kebabName: 'pictos-cartes06icon', importPath: './PictosCartes06Icon', component: PictosCartes06Icon },
  { name: 'PictosEditeurAjouterImageIcon', pascalName: 'PictosEditeurAjouterImageIcon', kebabName: 'pictos-editeur-ajouter-image-icon', importPath: './PictosEditeurAjouterImageIcon', component: PictosEditeurAjouterImageIcon },
  { name: 'PictosEditeurAjouterLienIcon', pascalName: 'PictosEditeurAjouterLienIcon', kebabName: 'pictos-editeur-ajouter-lien-icon', importPath: './PictosEditeurAjouterLienIcon', component: PictosEditeurAjouterLienIcon },
  { name: 'PictosEditeurAlignerDroiteIcon', pascalName: 'PictosEditeurAlignerDroiteIcon', kebabName: 'pictos-editeur-aligner-droite-icon', importPath: './PictosEditeurAlignerDroiteIcon', component: PictosEditeurAlignerDroiteIcon },
  { name: 'PictosEditeurAlignerGaucheIcon', pascalName: 'PictosEditeurAlignerGaucheIcon', kebabName: 'pictos-editeur-aligner-gauche-icon', importPath: './PictosEditeurAlignerGaucheIcon', component: PictosEditeurAlignerGaucheIcon },
  { name: 'PictosEditeurAlignerMilieuIcon', pascalName: 'PictosEditeurAlignerMilieuIcon', kebabName: 'pictos-editeur-aligner-milieu-icon', importPath: './PictosEditeurAlignerMilieuIcon', component: PictosEditeurAlignerMilieuIcon },
  { name: 'PictosEditeurCitationIcon', pascalName: 'PictosEditeurCitationIcon', kebabName: 'pictos-editeur-citation-icon', importPath: './PictosEditeurCitationIcon', component: PictosEditeurCitationIcon },
  { name: 'PictosEditeurCommentaireIcon', pascalName: 'PictosEditeurCommentaireIcon', kebabName: 'pictos-editeur-commentaire-icon', importPath: './PictosEditeurCommentaireIcon', component: PictosEditeurCommentaireIcon },
  { name: 'PictosEditeurCouleurBlancIcon', pascalName: 'PictosEditeurCouleurBlancIcon', kebabName: 'pictos-editeur-couleur-blanc-icon', importPath: './PictosEditeurCouleurBlancIcon', component: PictosEditeurCouleurBlancIcon },
  { name: 'PictosEditeurCouleurNoirIcon', pascalName: 'PictosEditeurCouleurNoirIcon', kebabName: 'pictos-editeur-couleur-noir-icon', importPath: './PictosEditeurCouleurNoirIcon', component: PictosEditeurCouleurNoirIcon },
  { name: 'PictosEditeurCouleurRougeIcon', pascalName: 'PictosEditeurCouleurRougeIcon', kebabName: 'pictos-editeur-couleur-rouge-icon', importPath: './PictosEditeurCouleurRougeIcon', component: PictosEditeurCouleurRougeIcon },
  { name: 'PictosEditeurDeroulerIcon', pascalName: 'PictosEditeurDeroulerIcon', kebabName: 'pictos-editeur-derouler-icon', importPath: './PictosEditeurDeroulerIcon', component: PictosEditeurDeroulerIcon },
  { name: 'PictosEditeurEncartIcon', pascalName: 'PictosEditeurEncartIcon', kebabName: 'pictos-editeur-encart-icon', importPath: './PictosEditeurEncartIcon', component: PictosEditeurEncartIcon },
  { name: 'PictosEditeurGrasIcon', pascalName: 'PictosEditeurGrasIcon', kebabName: 'pictos-editeur-gras-icon', importPath: './PictosEditeurGrasIcon', component: PictosEditeurGrasIcon },
  { name: 'PictosEditeurItaliqueIcon', pascalName: 'PictosEditeurItaliqueIcon', kebabName: 'pictos-editeur-italique-icon', importPath: './PictosEditeurItaliqueIcon', component: PictosEditeurItaliqueIcon },
  { name: 'PictosEditeurParagrapheIcon', pascalName: 'PictosEditeurParagrapheIcon', kebabName: 'pictos-editeur-paragraphe-icon', importPath: './PictosEditeurParagrapheIcon', component: PictosEditeurParagrapheIcon },
  { name: 'PictosEditeurPucesIcon', pascalName: 'PictosEditeurPucesIcon', kebabName: 'pictos-editeur-puces-icon', importPath: './PictosEditeurPucesIcon', component: PictosEditeurPucesIcon },
  { name: 'PictosEditeurSouligneIcon', pascalName: 'PictosEditeurSouligneIcon', kebabName: 'pictos-editeur-souligne-icon', importPath: './PictosEditeurSouligneIcon', component: PictosEditeurSouligneIcon },
  { name: 'PictosEditeurSurlignageBlancIcon', pascalName: 'PictosEditeurSurlignageBlancIcon', kebabName: 'pictos-editeur-surlignage-blanc-icon', importPath: './PictosEditeurSurlignageBlancIcon', component: PictosEditeurSurlignageBlancIcon },
  { name: 'PictosEditeurSurlignageNoirIcon', pascalName: 'PictosEditeurSurlignageNoirIcon', kebabName: 'pictos-editeur-surlignage-noir-icon', importPath: './PictosEditeurSurlignageNoirIcon', component: PictosEditeurSurlignageNoirIcon },
  { name: 'PictosEditeurSurlignageRougeIcon', pascalName: 'PictosEditeurSurlignageRougeIcon', kebabName: 'pictos-editeur-surlignage-rouge-icon', importPath: './PictosEditeurSurlignageRougeIcon', component: PictosEditeurSurlignageRougeIcon },
  { name: 'PictosEditeurTitre1Icon', pascalName: 'PictosEditeurTitre1Icon', kebabName: 'pictos-editeur-titre1icon', importPath: './PictosEditeurTitre1Icon', component: PictosEditeurTitre1Icon },
  { name: 'PictosEditeurTitre2Icon', pascalName: 'PictosEditeurTitre2Icon', kebabName: 'pictos-editeur-titre2icon', importPath: './PictosEditeurTitre2Icon', component: PictosEditeurTitre2Icon },
  { name: 'PictosEditeurTraitIcon', pascalName: 'PictosEditeurTraitIcon', kebabName: 'pictos-editeur-trait-icon', importPath: './PictosEditeurTraitIcon', component: PictosEditeurTraitIcon },
  { name: 'PictosModulesAnonymeIcon', pascalName: 'PictosModulesAnonymeIcon', kebabName: 'pictos-modules-anonyme-icon', importPath: './PictosModulesAnonymeIcon', component: PictosModulesAnonymeIcon },
  { name: 'PictosModulesChronologieIcon', pascalName: 'PictosModulesChronologieIcon', kebabName: 'pictos-modules-chronologie-icon', importPath: './PictosModulesChronologieIcon', component: PictosModulesChronologieIcon },
  { name: 'PictosModulesMettreEnAvantIcon', pascalName: 'PictosModulesMettreEnAvantIcon', kebabName: 'pictos-modules-mettre-en-avant-icon', importPath: './PictosModulesMettreEnAvantIcon', component: PictosModulesMettreEnAvantIcon },
  { name: 'PictosModulesValiderIcon', pascalName: 'PictosModulesValiderIcon', kebabName: 'pictos-modules-valider-icon', importPath: './PictosModulesValiderIcon', component: PictosModulesValiderIcon },
  { name: 'Placeholder01Icon', pascalName: 'Placeholder01Icon', kebabName: 'placeholder01icon', importPath: './Placeholder01Icon', component: Placeholder01Icon },
  { name: 'PoingIcon', pascalName: 'PoingIcon', kebabName: 'poing-icon', importPath: './PoingIcon', component: PoingIcon },
  { name: 'ProfilIcon', pascalName: 'ProfilIcon', kebabName: 'profil-icon', importPath: './ProfilIcon', component: ProfilIcon },
  { name: 'ReduireIcon', pascalName: 'ReduireIcon', kebabName: 'reduire-icon', importPath: './ReduireIcon', component: ReduireIcon },
  { name: 'RevueDePresseIcon', pascalName: 'RevueDePresseIcon', kebabName: 'revue-de-presse-icon', importPath: './RevueDePresseIcon', component: RevueDePresseIcon },
  { name: 'SaveIcon', pascalName: 'SaveIcon', kebabName: 'save-icon', importPath: './SaveIcon', component: SaveIcon },
  { name: 'TexteIcon', pascalName: 'TexteIcon', kebabName: 'texte-icon', importPath: './TexteIcon', component: TexteIcon },
  { name: 'TrashIcon', pascalName: 'TrashIcon', kebabName: 'trash-icon', importPath: './TrashIcon', component: TrashIcon },
  { name: 'TwitterIcon', pascalName: 'TwitterIcon', kebabName: 'twitter-icon', importPath: './TwitterIcon', component: TwitterIcon },
];
