name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@10 --activate
          node --version
          npm --version
          pnpm --version

      - run: pnpm install --no-frozen-lockfile

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm release
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: 'true'

      - name: Push tags
        if: ${{ steps.changesets.outputs.published == 'true' }}
        run: git push --follow-tags
